
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    command: /app/entrypoint.sh  # Явно указываем команду
    volumes:
    - ./backend:/app  # Осторожно! Монтирование после сборки
    depends_on:
      - postgres
    networks:
      - app-network


  postgres:
    image: postgres:latest

    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app-network
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge