# Generated by Django 5.1.7 on 2025-03-12 05:21

import core.apps.music.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to=core.apps.music.models.authors_collection_covers_directory_path)),
                ('author', models.ManyToManyField(to='music.author')),
            ],
        ),
        migrations.CreateModel(
            name='UsersCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to=core.apps.music.models.users_collection_covers_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to=core.apps.music.models.track_covers_directory_path)),
                ('author', models.ManyToManyField(to='music.author')),
                ('authors_collection', models.ManyToManyField(to='music.authorscollection')),
                ('users_collection', models.ManyToManyField(to='music.userscollection')),
            ],
        ),
    ]
