# Generated by Django 5.1.7 on 2025-03-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='authors_collection',
            field=models.ManyToManyField(blank=True, to='music.authorscollection'),
        ),
        migrations.AlterField(
            model_name='track',
            name='users_collection',
            field=models.ManyToManyField(blank=True, to='music.userscollection'),
        ),
    ]
