# Generated by Django 5.1.7 on 2025-03-19 05:29

import core.apps.music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_track_authors_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, upload_to=core.apps.music.models.track_audio_files_directory_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='authors_collection',
            field=models.ManyToManyField(blank=True, related_name='a_collection', to='music.authorscollection'),
        ),
        migrations.AlterField(
            model_name='track',
            name='users_collection',
            field=models.ManyToManyField(blank=True, related_name='u_collection', to='music.userscollection'),
        ),
    ]
