# Generated by Django 5.1.7 on 2025-03-19 05:33

import core.apps.music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_track_audio_file_alter_track_authors_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(upload_to=core.apps.music.models.track_audio_files_directory_path),
        ),
    ]
