# Generated by Django 5.1.7 on 2025-04-09 11:10

import core.apps.music.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_track_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authorscollection',
            name='tracks',
            field=models.ManyToManyField(related_name='track_author_collections', to='music.track'),
        ),
        migrations.AddField(
            model_name='track',
            name='user_of_likes',
            field=models.ManyToManyField(related_name='likes_of_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userscollection',
            name='tracks',
            field=models.ManyToManyField(related_name='track_user_collections', to='music.track'),
        ),
        migrations.AlterField(
            model_name='authorscollection',
            name='author',
            field=models.ManyToManyField(related_name='play_lists', to='music.author'),
        ),
        migrations.AlterField(
            model_name='authorscollection',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=core.apps.music.models.authors_collection_covers_directory_path),
        ),
        migrations.AlterField(
            model_name='authorscollection',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='authorscollection',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, default='images/covers/tracks/default/track.jpg', null=True, upload_to=core.apps.music.models.track_covers_directory_path),
        ),
        migrations.AlterField(
            model_name='userscollection',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=core.apps.music.models.users_collection_covers_directory_path),
        ),
        migrations.AlterField(
            model_name='userscollection',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userscollection',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
