# Generated by Django 5.1.7 on 2025-04-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_userscollection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='author',
            field=models.ManyToManyField(related_name='tracks', to='music.author'),
        ),
    ]
