# Generated by Django 5.1.7 on 2025-04-17 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_track_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authorscollection',
            name='user_of_likes',
            field=models.ManyToManyField(related_name='likes_of_authora_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
