# Generated by Django 5.1.7 on 2025-04-17 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_authorscollection_user_of_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorscollection',
            name='user_of_likes',
            field=models.ManyToManyField(blank=True, related_name='likes_of_authora_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='user_of_likes',
            field=models.ManyToManyField(blank=True, related_name='likes_of_tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
