# Generated by Django 5.1.7 on 2025-04-19 14:20

import core.apps.music.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_authorscollection_user_of_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorscollection',
            name='tracks',
            field=models.ManyToManyField(blank=True, null=True, related_name='track_author_collections', to='music.track'),
        ),
        migrations.AlterField(
            model_name='authorscollection',
            name='user_of_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes_of_authora_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='track',
            name='user_of_likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes_of_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userscollection',
            name='cover',
            field=models.ImageField(blank=True, default='images/covers/u_collections/default/default_u_col.png', null=True, upload_to=core.apps.music.models.users_collection_covers_directory_path),
        ),
        migrations.AlterField(
            model_name='userscollection',
            name='tracks',
            field=models.ManyToManyField(blank=True, null=True, related_name='track_user_collections', to='music.track'),
        ),
    ]
