# Generated by Django 5.2.1 on 2025-05-24 04:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_userscollection_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)'),
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_completed', models.BooleanField(default=False)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to='music.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Listening Histories',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['user', 'date'], name='music_liste_user_id_534ea4_idx'), models.Index(fields=['track'], name='music_liste_track_i_b746a4_idx'), models.Index(fields=['is_completed'], name='music_liste_is_comp_7e9c92_idx')],
            },
        ),
    ]
